In [2]:
text="""Hi! How are you doing today?
What's up with you right now?
How are you doing these days buddy?
Nothing much, just chilling at home today.
What are you up to right now?
Just chilling at home watching some TV.
Do you have any plans for weekend?
I am going hiking with my friends tomorrow.
That sounds like a lot of fun!
Where exactly are you planning to go?
We are going to Mount Diablo for hiking.
How is your day going so far today?
Pretty good, how about yours going on?
I am feeling a bit tired today honestly.
Did you manage to sleep well tonight?
Not really, I stayed up late working.
What were you doing so late tonight?
I was working on my college assignments.
That sounds really tough for you man.
When is the deadline for your assignment?
The deadline is actually tomorrow morning early.
You better finish it up really quick.
Yeah, I am feeling so stressed right now.
Do not worry, you will definitely make it happen.
Thanks a lot for all the support.
No problem at all, anytime you need.
Have you eaten your lunch yet today?
Not yet, I am feeling really hungry now.
Do you want to grab something together?
Sure, where do you think we should go?
How about we try that new cafe?
That sounds really good to me honestly.
What time actually works for you today?
Maybe we can meet around 1 PM?
That is perfect timing, see you there then.
Are you free to hang out tonight?
Yeah I am, what is the plan exactly?
Should we watch a movie or dinner?
Let us do both if that works out!
Which movie do you want to watch?
I have not decided on that yet honestly.
You should check what is playing right now.
I will do that right now quickly.
The weather is really nice today outside.
Yeah, it is finally sunny after so long.
It has been raining all week long here.
I really hate the rain so much.
Me too, it makes everything so gloomy.
Rain makes me want to stay inside.
I feel exactly the same way honestly.
Do you have any coffee at home?
I just made some fresh coffee now.
Can I please get a cup too?
Of course, come over to my place.
Thanks so much, you are the best friend.
Anytime at all, that is what friends do.
How is your work going on these days?
It has been pretty busy for me lately.
Are you having lots of meetings daily?
Yeah, they are all back to back today.
That must be really exhausting for you.
Tell me about it, I am so tired.
I think I need a break very soon.
You should take the weekend off completely.
I am planning to do exactly that tomorrow.
That is definitely a really good idea mate.
Are you coming to the party tomorrow?
Wait, which party are you talking about?
The one that is happening on Saturday night.
Oh yeah, I will definitely be there surely.
Great, it is going to be so fun!
Who else is coming to the party?
Most of our close friends are coming.
It should be a really good time.
What should I bring to the party?
Just bring yourself, that is all we need.
Okay, that sounds pretty easy to me.
Alright, see you there tomorrow night then!
I really cannot wait for it honestly.
Me neither, it will be absolutely amazing time.
Is your phone working properly right now?
Yeah it is, why are you asking?
My phone is acting really weird today.
Maybe you should try restarting it now.
I already tried doing that earlier today.
It could be the battery causing problems.
I might need to charge it fully.
That is actually a really good point here.
How is your family doing these days now?
They are all doing really well, thanks asking.
That is really good to hear from you.
Please send them all my warm regards.
I will definitely do that, thanks again.
Should we meet at your place today?
Let us try to meet halfway between us.
That is definitely fair enough for both of us.
Where exactly should we meet then today?
How about we meet at the mall?
That location works perfectly for me today.
What time should we plan to meet?
How about we meet around 5 PM?
That is absolutely perfect timing for me too.
Alright, see you there very soon then.
You take care of yourself till then.
You too, stay safe on your way!
I love you so much my dear.
I love you too with all heart.
Em chesthunnav ra ippudu ekkada unnav?
Nenu ippudu room lo unna ra bro.
College ki raledu ivala enduku raledu ra?
Ledu ra, bunk kotta feeling ledu.
Class ela undi cheppu ra details ga?
Bore ga undi baaga teacher explanation kuda poor.
Teacher attendance thisara class lo ippudu ra?
Ledu ra, lucky escape ayyindi mana ki.
Bayata veldam ra konni sepu time pass.
Ekkada ki veldham cheppu decide chesuko ra?
Coffee thaddam ra baaga thagali undi mood.
Sare, epudu start avvali cheppu time ra?
Ippude start avvu late ayyithe problem ra.
Okay, ready avthunna nenu ippude veltunna ra.
Time ekkuva pattadu ra fast ga raa.
Fast ga raa traffic undi emo bro.
Traffic undi emo leka pothe cab tesko.
Sare, chustha situation batti decide chestha ra.
Reach ayyava leda inka time pattunda cheppu?
Inkonchem time pattundi wait cheyyi ra please.
Tension padaku nenu osthunna fast ga bro.
Late ayyanu ra sorry time management cheyyaledu.
Parledu ra problem ledu tension padaku bro.
Order chesava leda inka wait cheyyala ra?
Inka cheyaledu nuvvu vacchaka cheddam ra.
Menu choodu em theesukovali decide chesuko ra.
Em theesukovali cheppu naku confusion ga undi.
Coffee strong ga undali latte kadu regular.
Snacks kuda tesko mana full ga tindam.
Pakka teskunta nenu fries and sandwich bro.
Bill evaru isthar decide chesukovali ippude ra?
Share cheddam fair ga split cheddham ra.
Okay done next time nenu full istha.
Sure thing completely no problem at all.
Weekend plans emaina unnaya cheppu details ga?
Inka decide cheyyaledu nuvvu suggest cheyi ra.
Movie veldama konni sepu enjoy cheddam ra?
Oo good idea which movie let's decide.
Ticket book cheyamanta online lo check chesthe.
Online lo chusta available seats unnaya leda.
Seat dorikinda balcony seats or normal seats?
Balcony dorikindi premium seats with good view.
Perfect anthe ga mana experience super untundi!
Time cheppu exactly what time should we go?
Evening 6 ki show first show anthaga.
Sare, appude ostha ready ga undadam ra.
Interval ki popcorn teskunta nuvvu kuda tesko.
Nachos kuda tisko caramel popcorn kuda bro.
Full set ga tesko food antha share.
Enjoy cheddam full ga relax ayyi chuddam.
Exam ela ayyindi ra result eppudu ostundi?
Chala kashtam ayyindi paper tough ga undhi.
Prepare cheyyaledu ga time undhi leda ra?
Time ledu ra busy ga unna last week.
Next time planning pettu proper ga cheddam study.
Definite ga cheddam next time serious ga focus.
Notes unnaya nee dhaggara naaku kavali bro?
Konni unnay naa dhaggara part wise inka.
Pampu ra please naaku chaala avasaram undi.
Photo petti pampista nuvvu print chesko ekkada.
Thanks a lot ra chaala help ayyindi nuvvu.
Mention cheyyaku ra friends ki help cheyyali.
Hostel lo unnavaa leda intlo unnava ippudu?
Ledu, ghar pe unna hostel kaadu bro.
Room shift ayyava nuvvu new room ki?
Avnu, last week shift ayyanu better place.
New room ela undi cheppu experience share.
Chaala better undi spacious and clean ga.
Roommate manchivada leda attitude ekkuva unda?
Avnu, cool guy adjusting nature manchidhi.
Share chesko easy ga space and things.
Adi advantage ra compatible ga undhi manaki.
Lunch chesava leda inka kavali neeku ra?
Just chesesa ippude tinna full ga bro.
Em chesav cheppu home food or outside?
Simple rice curry homemade tiffin techchukunnanu ra.
Mess food ela undi taste baagunda ekkada?
Okay okay, average antha great kaadu honestly.
Canteen better kada quality wise compare chesthe?
Pakka, next time canteen lone order cheddam.
Mobile recharge chesukovali urgent ga naaku ippudu.
Balance ekkuva unda leda almost khatam ayyinda?
Almost finish ayyipoyindi recharge cheyyali urgent ga.
Recharge chesi pettu fast ga data kavali.
Plan enti needu unlimited or limited plan?
Unlimited plan teesukunnanu data ekkuva use aithundi.
Cost ekkuva kada monthly ga spend avthundi?
Antha ledu reasonable price lo milthundi bro.
Worth it anukunna investment wise manchi plan.
Data ekkuva kavali streaming and downloads ki.
Yeah, streaming kosam youtube chaala chustha daily.
Same here ra addiction ayyindi aa app ki.
Inka em cheyyalo decide cheyyi plan cheppu.
Chill kottu simple ga relax ga time pass.
Nenu neను chaala istam ra love you.
Nenu kuda neను chaala istam love you too.
Kya kar raha hai tu abhi kaha hai?
Main abhi room mein hu yaar ghar pe.
College nahi gaya kya aaj subah tu bhi?
Nahi yaar, bunk maar diya mood nahi tha.
Class kaisi thi batao kuch details mein?
Bahut boring thi yaar teacher bhi bekaar tha.
Teacher ne attendance li kya class mein today?
Nahi yaar, lucky tha aaj humara bahut.
Bahar chalte hai thoda time spend karte.
Kaha jaana hai batao decide kar le yaar?
Coffee peete hai bahut pine ka man hai.
Theek hai, kab chalein time bata do?
Abhi nikal late ho jayega phir problem hogi.
Okay, ready ho raha hu main jaldi aata.
Zyada time mat le fast aa jao yaar.
Jaldi aa yaar traffic bhi ho sakta hai.
Traffic toh nahi hai na lena mat tension?
Nahi toh cab le lio asaan rahega bro.
Theek hai, dekhta hu situation dekh ke decide.
Pahuch gaya kya ya abhi time lagega batao?
Thoda aur time lagega wait kar lo please.
Tension mat le main aa raha hu fast.
Sorry late ho gaya yaar time manage nahi hua.
Koi baat nahi yaar problem nahi hai bilkul.
Order kiya kya ya wait karna hai abhi?
Abhi nahi kiya tera aane ka wait kar.
Menu dekh le kya lena hai decide karlo.
Kya lena hai batao confusion ho raha hai.
Coffee strong chahiye latte nahi regular coffee better.
Snacks bhi le lo thoda khane ka man hai.
Pakka lunga main fries aur sandwich bhi order.
Bill kaun dega decide kar lete hain abhi?
Share kar lete hai fair way mein split.
Okay done next time main full bill dunga.
Sure bhai bilkul koi problem nahi hai yaar.
Weekend ke plans kya hai kuch batao details?
Abhi decide nahi kiya tu suggest kar yaar.
Movie dekhne chalein thoda enjoy kar lete hain?
Haan good idea kaun si movie decide karte.
Ticket book kar du online check karta hu?
Online dekh le available seats hain ya nahi.
Seat mil gayi kya balcony ya normal seats?
Balcony mil gayi premium seats with best view.
Perfect hai yaar experience bahut accha hoga definitely!
Time bata exactly kitne baje jaana hai?
Shaam 6 baje show hai first show time.
Theek hai, aa jaunga ready rehna tu bhi.
Interval mein popcorn lenge tu bhi le liyo.
Nachos bhi le lena caramel popcorn bhi share.
Full maza karenge saara food share kar lenge.
Enjoy karenge full relax hokar dekhenge movie ache.
Exam kaisa gaya yaar result kab aayega batao?
Bahut hard tha yaar paper ekdum tough tha.
Prepare nahi kiya tha kya time nahi mila?
Time hi nahi mila yaar busy tha last week.
Next time plan kar lena proper se padhai karna.
Zaroor karunga next time serious focus rakhunga definitely.
Notes hai tere paas mujhe chahiye yaar urgent?
Kuch hai mere paas part wise aur bhi hai.
Bhej de please yaar bahut zaroorat hai urgent.
Photo leke bhejta hu tu print karwa lena.
Thanks yaar bahut help ho gayi teri wajah se.
Koi baat nahi yaar dost ki help karni.
Hostel mein ho kya ya ghar pe ho?
Nahi, ghar pe hu hostel nahi shift hua.
Room shift ho gaya kya naye room mein?
Haan, last week shift ho gaya better place.
Naya room kaisa hai experience batao details mein?
Bahut better hai spacious aur clean bhi hai.
Roommate kaisa hai attitude thik hai ya problem?
Accha hai yaar cool banda adjusting nature hai.
Share karna easy hai space aur sab cheez.
Haan, ek advantage hai compatible hai bahut accha.
Lunch kar liya kya ya abhi karna hai?
Abhi kiya bas thoda time pehle khaya tha.
Kya khaya batao ghar ka khana ya bahar?
Simple dal chawal homemade tiffin laya tha ghar se.
Mess ka khana kaisa hai taste accha hai?
Theek thaak hai yaar itna accha nahi honestly.
Canteen better hai na quality wise compare karo?
Haan yaar next time canteen se order karenge.
Mobile recharge karna hai urgent bahut zaroori hai.
Balance kitna hai ya almost khatam ho gaya?
Almost khatam hai urgent recharge karna padega fast.
Recharge kar le jaldi data bahut chahiye urgent.
Plan kaun sa hai tera unlimited ya limited?
Unlimited plan hai mera data zyada use hota hai.
Zyada paisa lagta hai monthly mein spend hota?
Itna nahi yaar reasonable price mein mil jata.
Worth hai lagta hai investment wise accha plan hai.
Data zyada chahiye streaming aur downloads ke liye.
Haan yaar streaming ke liye youtube bahut dekhta.
Same here yaar addiction ho gayi hai app.
Aur kya kare ab decide kar plan batao.
Chill marte hai simple relax karke time pass.
Main tumhe bahut pyaar karta hu yaar sach.
Main bhi tumhe bahut pyaar karti hu love you too."""

In [3]:
type(text)

str

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


In [5]:
tokenizer=Tokenizer()

In [6]:
tokenizer.fit_on_texts([text])

In [7]:
vocabulary=tokenizer.word_index

In [8]:
vocabulary

{'hai': 1,
 'you': 2,
 'ra': 3,
 'time': 4,
 'ga': 5,
 'yaar': 6,
 'i': 7,
 'is': 8,
 'that': 9,
 'nahi': 10,
 'to': 11,
 'it': 12,
 'really': 13,
 'the': 14,
 'kya': 15,
 'are': 16,
 'today': 17,
 'decide': 18,
 'kar': 19,
 'bahut': 20,
 'do': 21,
 'for': 22,
 'we': 23,
 'plan': 24,
 'bhi': 25,
 'ho': 26,
 'should': 27,
 'bro': 28,
 'now': 29,
 'a': 30,
 'so': 31,
 'all': 32,
 'ki': 33,
 'undi': 34,
 'cheppu': 35,
 'abhi': 36,
 'mein': 37,
 'le': 38,
 'ya': 39,
 'how': 40,
 'what': 41,
 'good': 42,
 'me': 43,
 'hu': 44,
 'tha': 45,
 'batao': 46,
 'at': 47,
 'your': 48,
 'better': 49,
 'problem': 50,
 'room': 51,
 'lo': 52,
 'leda': 53,
 'full': 54,
 'share': 55,
 'next': 56,
 'am': 57,
 'exactly': 58,
 'honestly': 59,
 'yeah': 60,
 'definitely': 61,
 'meet': 62,
 'movie': 63,
 'too': 64,
 'coffee': 65,
 'wait': 66,
 'okay': 67,
 'nenu': 68,
 'ledu': 69,
 'fast': 70,
 'inka': 71,
 'cheddam': 72,
 'seats': 73,
 'urgent': 74,
 'main': 75,
 'gaya': 76,
 'aur': 77,
 'doing': 78,
 'right': 

In [9]:
vocabulary_size=len(vocabulary)+1

In [10]:
vocabulary_size

731

In [11]:
sequences=[]
for sentence in text.split("\n"):
    tokenized_sen=tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1,len(tokenized_sen)):
        n_gram_sequence=tokenized_sen[:i+1]
        sequences.append(n_gram_sequence)

In [12]:
sequences

[[227, 40],
 [227, 40, 16],
 [227, 40, 16, 2],
 [227, 40, 16, 2, 78],
 [227, 40, 16, 2, 78, 17],
 [401, 119],
 [401, 119, 101],
 [401, 119, 101, 2],
 [401, 119, 101, 2, 79],
 [401, 119, 101, 2, 79, 29],
 [40, 16],
 [40, 16, 2],
 [40, 16, 2, 78],
 [40, 16, 2, 78, 172],
 [40, 16, 2, 78, 172, 173],
 [40, 16, 2, 78, 172, 173, 402],
 [403, 120],
 [403, 120, 102],
 [403, 120, 102, 228],
 [403, 120, 102, 228, 47],
 [403, 120, 102, 228, 47, 121],
 [403, 120, 102, 228, 47, 121, 17],
 [41, 16],
 [41, 16, 2],
 [41, 16, 2, 119],
 [41, 16, 2, 119, 11],
 [41, 16, 2, 119, 11, 79],
 [41, 16, 2, 119, 11, 79, 29],
 [102, 228],
 [102, 228, 47],
 [102, 228, 47, 121],
 [102, 228, 47, 121, 404],
 [102, 228, 47, 121, 404, 229],
 [102, 228, 47, 121, 404, 229, 405],
 [21, 2],
 [21, 2, 122],
 [21, 2, 122, 230],
 [21, 2, 122, 230, 174],
 [21, 2, 122, 230, 174, 22],
 [21, 2, 122, 230, 174, 22, 123],
 [7, 57],
 [7, 57, 80],
 [7, 57, 80, 231],
 [7, 57, 80, 231, 101],
 [7, 57, 80, 231, 101, 81],
 [7, 57, 80, 231, 10

In [13]:
max_seq_len=max([len(seq) for seq in sequences])

In [14]:
max_seq_len

10

In [15]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
paded_sequences=pad_sequences(sequences,maxlen=max_seq_len,padding='pre')

In [16]:
paded_sequences

array([[  0,   0,   0, ...,   0, 227,  40],
       [  0,   0,   0, ..., 227,  40,  16],
       [  0,   0,   0, ...,  40,  16,   2],
       ...,
       [  0,   0,  75, ..., 730,  44, 107],
       [  0,  75,  25, ...,  44, 107,   2],
       [ 75,  25, 399, ..., 107,   2,  64]])

In [17]:
X=paded_sequences[:,:-1]
y=paded_sequences[:,-1]

In [18]:
X

array([[  0,   0,   0, ...,   0,   0, 227],
       [  0,   0,   0, ...,   0, 227,  40],
       [  0,   0,   0, ..., 227,  40,  16],
       ...,
       [  0,   0,  75, ..., 400, 730,  44],
       [  0,  75,  25, ..., 730,  44, 107],
       [ 75,  25, 399, ...,  44, 107,   2]])

In [19]:
y

array([ 40,  16,   2, ..., 107,   2,  64])

In [20]:
len(y)

1943

In [21]:
y.shape

(1943,)

In [22]:
#Convert y to catergorical y (One Hot Encoding)
from tensorflow.keras.utils import to_categorical   
y=to_categorical(y,num_classes=vocabulary_size)

In [23]:
y.shape

(1943, 731)

In [24]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [26]:
model = Sequential()
model.add(Embedding(input_dim=vocabulary_size,output_dim=200,input_shape=(max_seq_len-1,)))
model.add(LSTM(150))
model.add(Dense(vocabulary_size,activation='softmax'))

C:\Users\Sufiyan Sami\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [27]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [28]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 9, 200)         │       146,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       210,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 731)            │       110,381 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 467,181 (1.78 MB)

 Trainable params: 467,181 (1.78 MB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.fit(X,y,epochs=100)

Epoch 1/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.0118 - loss: 6.4514
Epoch 2/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.0283 - loss: 6.1069
Epoch 3/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.0283 - loss: 6.0083
Epoch 4/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.0437 - loss: 5.8239
Epoch 5/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.0633 - loss: 5.5038
Epoch 6/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.0865 - loss: 5.1789
Epoch 7/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.1024 - loss: 4.8535
Epoch 8/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.1348 - loss: 4.5431
Epoch 9/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1740 - loss: 4.2272
Epoch 10/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2110 - loss: 3.9188
Epoch 11/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2640 - loss: 3.6198
Epoch 12/100
61/61 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - 

In [34]:
input="kya"

tokenized_input=tokenizer.texts_to_sequences([input])[0]
print(tokenized_input)
paded_tokenized_input=pad_sequences([tokenized_input],maxlen=max_seq_len-1,padding='pre')
print(paded_tokenized_input)
val=np.argmax(model.predict(paded_tokenized_input))
print(val)

for word, index in tokenizer.word_index.items():
    if index==val:
        print("Next word is:",word)

[15]
[[ 0  0  0  0  0  0  0  0 15]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step
393
Next word is: khaya
